name: Static code analysis

on:
  workflow_dispatch: {}
jobs:
  performAnalysis:
    name: Perform static code analysis using Project Auditor
    runs-on: ubuntu-latest
    container: unityci/editor:2019.4.34f1-base-0
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-